[package]
name = "tor_get_request"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["socks", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
